# Generated by Django 5.1.4 on 2024-12-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('comptabilisation', models.BooleanField(default=False)),
                ('demande_mise_a_jour', models.BooleanField(default=False)),
                ('piece_desequilibre', models.BooleanField(default=False)),
                ('difference_operationnelle_comptabilite', models.BooleanField(default=False)),
                ('balance_equilibree', models.BooleanField(default=False)),
                ('journee_fermee', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
