# Generated by Django 5.1.4 on 2024-12-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
