# Generated by Django 5.1.4 on 2025-01-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0007_remove_agence_comptabilisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
