# Generated by Django 5.1.4 on 2025-01-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0008_timeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
