# Generated by Django 5.1.4 on 2025-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0009_delete_timeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
